// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from '../flatbuffers/flatbuffers';



export class Vec4 {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Vec4 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

x():number {
  return this.bb!.readFloat32(this.bb_pos);
}

y():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

z():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
}

w():number {
  return this.bb!.readFloat32(this.bb_pos + 12);
}

static sizeOf():number {
  return 16;
}

static createVec4(builder:flatbuffers.Builder, x: number, y: number, z: number, w: number):flatbuffers.Offset {
  builder.prep(4, 16);
  builder.writeFloat32(w);
  builder.writeFloat32(z);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
}


unpack(): Vec4T {
  return new Vec4T(
    this.x(),
    this.y(),
    this.z(),
    this.w()
  );
}


unpackTo(_o: Vec4T): void {
  _o.x = this.x();
  _o.y = this.y();
  _o.z = this.z();
  _o.w = this.w();
}
}

export class Vec4T {
constructor(
  public x: number = 0.0,
  public y: number = 0.0,
  public z: number = 0.0,
  public w: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Vec4.createVec4(builder,
    this.x,
    this.y,
    this.z,
    this.w
  );
}
}
