"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.Squat = void 0;
var flatbuffers = require("../../../../app/src/wasm/flatbuffers/flatbuffers");
var Squat = /** @class */ (function () {
    function Squat() {
        this.bb = null;
        this.bb_pos = 0;
    }
    Squat.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    Squat.getRootAsSquat = function (bb, obj) {
        return (obj || new Squat()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Squat.getSizePrefixedRootAsSquat = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Squat()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Squat.prototype.status = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    };
    Squat.startSquat = function (builder) {
        builder.startObject(1);
    };
    Squat.addStatus = function (builder, status) {
        builder.addFieldFloat32(0, status, 0.0);
    };
    Squat.endSquat = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    Squat.createSquat = function (builder, status) {
        Squat.startSquat(builder);
        Squat.addStatus(builder, status);
        return Squat.endSquat(builder);
    };
    return Squat;
}());
exports.Squat = Squat;
