"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.TestC = void 0;
var flatbuffers = require("./flatbuffers.js");
var TestC = /** @class */ (function () {
    function TestC() {
        this.bb = null;
        this.bb_pos = 0;
    }
    TestC.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    TestC.getRootAsTestC = function (bb, obj) {
        return (obj || new TestC()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    TestC.getSizePrefixedRootAsTestC = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new TestC()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    TestC.prototype.name = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    TestC.startTestC = function (builder) {
        builder.startObject(1);
    };
    TestC.addName = function (builder, nameOffset) {
        builder.addFieldOffset(0, nameOffset, 0);
    };
    TestC.endTestC = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    TestC.finishTestCBuffer = function (builder, offset) {
        builder.finish(offset);
    };
    TestC.finishSizePrefixedTestCBuffer = function (builder, offset) {
        builder.finish(offset, undefined, true);
    };
    TestC.createTestC = function (builder, nameOffset) {
        TestC.startTestC(builder);
        TestC.addName(builder, nameOffset);
        return TestC.endTestC(builder);
    };
    return TestC;
}());
exports.TestC = TestC;
