// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from '../flatbuffers/flatbuffers';



export class Client {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Client {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClient(bb:flatbuffers.ByteBuffer, obj?:Client):Client {
  return (obj || new Client()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClient(bb:flatbuffers.ByteBuffer, obj?:Client):Client {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Client()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

useJson():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startClient(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addUseJson(builder:flatbuffers.Builder, useJson:boolean) {
  builder.addFieldInt8(1, +useJson, +false);
}

static endClient(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishClientBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedClientBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createClient(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, useJson:boolean):flatbuffers.Offset {
  Client.startClient(builder);
  Client.addId(builder, idOffset);
  Client.addUseJson(builder, useJson);
  return Client.endClient(builder);
}

unpack(): ClientT {
  return new ClientT(
    this.id(),
    this.useJson()
  );
}


unpackTo(_o: ClientT): void {
  _o.id = this.id();
  _o.useJson = this.useJson();
}
}

export class ClientT {
constructor(
  public id: string|Uint8Array|null = null,
  public useJson: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);

  return Client.createClient(builder,
    id,
    this.useJson
  );
}
}
