// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { FeatureConfig } from '../feature-configs/feature-config';


export class FeatureConfigList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):FeatureConfigList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFeatureConfigList(bb:flatbuffers.ByteBuffer, obj?:FeatureConfigList):FeatureConfigList {
  return (obj || new FeatureConfigList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFeatureConfigList(bb:flatbuffers.ByteBuffer, obj?:FeatureConfigList):FeatureConfigList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FeatureConfigList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

configs(index: number, obj?:FeatureConfig):FeatureConfig|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new FeatureConfig()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

configsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startFeatureConfigList(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addConfigs(builder:flatbuffers.Builder, configsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, configsOffset, 0);
}

static createConfigsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startConfigsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endFeatureConfigList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishFeatureConfigListBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedFeatureConfigListBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createFeatureConfigList(builder:flatbuffers.Builder, configsOffset:flatbuffers.Offset):flatbuffers.Offset {
  FeatureConfigList.startFeatureConfigList(builder);
  FeatureConfigList.addConfigs(builder, configsOffset);
  return FeatureConfigList.endFeatureConfigList(builder);
}
}
