"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.FeatureConfig = void 0;
var flatbuffers = require("../../../../app/src/wasm/flatbuffers/flatbuffers");
var FeatureConfig = /** @class */ (function () {
    function FeatureConfig() {
        this.bb = null;
        this.bb_pos = 0;
    }
    FeatureConfig.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    FeatureConfig.getRootAsFeatureConfig = function (bb, obj) {
        return (obj || new FeatureConfig()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    FeatureConfig.getSizePrefixedRootAsFeatureConfig = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new FeatureConfig()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    FeatureConfig.prototype.featureId = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    FeatureConfig.prototype.enable = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
    };
    FeatureConfig.prototype.mutate_enable = function (value) {
        var offset = this.bb.__offset(this.bb_pos, 6);
        if (offset === 0) {
            return false;
        }
        this.bb.writeInt8(this.bb_pos + offset, +value);
        return true;
    };
    FeatureConfig.prototype.action = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    FeatureConfig.prototype.data = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    FeatureConfig.startFeatureConfig = function (builder) {
        builder.startObject(4);
    };
    FeatureConfig.addFeatureId = function (builder, featureIdOffset) {
        builder.addFieldOffset(0, featureIdOffset, 0);
    };
    FeatureConfig.addEnable = function (builder, enable) {
        builder.addFieldInt8(1, +enable, +false);
    };
    FeatureConfig.addAction = function (builder, actionOffset) {
        builder.addFieldOffset(2, actionOffset, 0);
    };
    FeatureConfig.addData = function (builder, dataOffset) {
        builder.addFieldOffset(3, dataOffset, 0);
    };
    FeatureConfig.endFeatureConfig = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    FeatureConfig.createFeatureConfig = function (builder, featureIdOffset, enable, actionOffset, dataOffset) {
        FeatureConfig.startFeatureConfig(builder);
        FeatureConfig.addFeatureId(builder, featureIdOffset);
        FeatureConfig.addEnable(builder, enable);
        FeatureConfig.addAction(builder, actionOffset);
        FeatureConfig.addData(builder, dataOffset);
        return FeatureConfig.endFeatureConfig(builder);
    };
    return FeatureConfig;
}());
exports.FeatureConfig = FeatureConfig;
