// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WALKDATA_WALKDATA_H_
#define FLATBUFFERS_GENERATED_WALKDATA_WALKDATA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 6,
             "Non-compatible flatbuffers version included");

namespace walkData {

struct Walk;
struct WalkBuilder;

struct Walk FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef WalkBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LEGUP = 4,
    VT_FREQUENCY = 6,
    VT_STRENGTH = 8
  };
  float legUp() const {
    return GetField<float>(VT_LEGUP, 0.0f);
  }
  bool mutate_legUp(float _legUp = 0.0f) {
    return SetField<float>(VT_LEGUP, _legUp, 0.0f);
  }
  float frequency() const {
    return GetField<float>(VT_FREQUENCY, 0.0f);
  }
  bool mutate_frequency(float _frequency = 0.0f) {
    return SetField<float>(VT_FREQUENCY, _frequency, 0.0f);
  }
  float strength() const {
    return GetField<float>(VT_STRENGTH, 0.0f);
  }
  bool mutate_strength(float _strength = 0.0f) {
    return SetField<float>(VT_STRENGTH, _strength, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_LEGUP, 4) &&
           VerifyField<float>(verifier, VT_FREQUENCY, 4) &&
           VerifyField<float>(verifier, VT_STRENGTH, 4) &&
           verifier.EndTable();
  }
};

struct WalkBuilder {
  typedef Walk Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_legUp(float legUp) {
    fbb_.AddElement<float>(Walk::VT_LEGUP, legUp, 0.0f);
  }
  void add_frequency(float frequency) {
    fbb_.AddElement<float>(Walk::VT_FREQUENCY, frequency, 0.0f);
  }
  void add_strength(float strength) {
    fbb_.AddElement<float>(Walk::VT_STRENGTH, strength, 0.0f);
  }
  explicit WalkBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Walk> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Walk>(end);
    return o;
  }
};

inline flatbuffers::Offset<Walk> CreateWalk(
    flatbuffers::FlatBufferBuilder &_fbb,
    float legUp = 0.0f,
    float frequency = 0.0f,
    float strength = 0.0f) {
  WalkBuilder builder_(_fbb);
  builder_.add_strength(strength);
  builder_.add_frequency(frequency);
  builder_.add_legUp(legUp);
  return builder_.Finish();
}

inline const walkData::Walk *GetWalk(const void *buf) {
  return flatbuffers::GetRoot<walkData::Walk>(buf);
}

inline const walkData::Walk *GetSizePrefixedWalk(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<walkData::Walk>(buf);
}

inline Walk *GetMutableWalk(void *buf) {
  return flatbuffers::GetMutableRoot<Walk>(buf);
}

inline walkData::Walk *GetMutableSizePrefixedWalk(void *buf) {
  return flatbuffers::GetMutableSizePrefixedRoot<walkData::Walk>(buf);
}

inline bool VerifyWalkBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<walkData::Walk>(nullptr);
}

inline bool VerifySizePrefixedWalkBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<walkData::Walk>(nullptr);
}

inline void FinishWalkBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<walkData::Walk> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedWalkBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<walkData::Walk> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace walkData

#endif  // FLATBUFFERS_GENERATED_WALKDATA_WALKDATA_H_
